name = "cloudflare-project"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = "src"

# Pages 发布配置
publish = ".next"

# Pages 配置
[env.production]
name = "cloudflare-project"

[env.preview]
name = "cloudflare-project-preview"

# 环境变量
[vars]
NODE_ENV = "production"